spring.application.name=backend-core

spring.datasource.url=jdbc:postgresql://localhost:5433/sortify_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true