spring.application.name=backend-core

spring.datasource.url=jdbc:postgresql://localhost:5433/sortify_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=ReplaceThisWithA256BitSecretKeyThatIsAtLeast32CharactersLong
jwt.expiration=3600000

# Multipart upload limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=50MB