CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'RECRUITER'))
);

CREATE TABLE jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    jd TEXT NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_jobs_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_jobs_status CHECK (status IN ('OPEN', 'CLOSED'))
);

CREATE INDEX idx_jobs_user_id ON jobs (user_id);

CREATE TABLE candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    name VARCHAR(200),
    email VARCHAR(255),
    score DOUBLE PRECISION,
    resume_key TEXT,
    status VARCHAR(32) NOT NULL,
    failure_reason TEXT,
    processed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_candidates_job FOREIGN KEY (job_id) REFERENCES jobs (id),
    CONSTRAINT ck_candidates_status CHECK (status IN ('PENDING', 'UPLOADED', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_candidates_score CHECK (score IS NULL OR (score >= 0 AND score <= 100))
);

CREATE INDEX idx_candidates_job_score ON candidates (job_id, score DESC);
CREATE INDEX idx_candidates_status ON candidates (status);
